server {
    listen 80;
    server_name localhost;

    # Docusaurus 정적 파일 제공
    location /wiki {
        alias /usr/share/nginx/html/wiki;
        index index.html index.htm;
        try_files $uri $uri/ /wiki/index.html;
    }

    # SPA 라우팅 호환을 위해 설정
    error_page 404 /wiki/404.html;
}
