FROM node:22-alpine
WORKDIR /app

# This container is designed to just build the react app and exit.
# Volumes should be mounted to /app when running this container.
CMD ["sh", "-c", "npm install && npm run build"]
