server {
    listen 80;

    client_max_body_size 200M;

    location / {
        root /app/html;
        index index.html;
        try_files $uri $uri/ =404;
    }

    # certbot 인증용
    location /.well-known/acme-challenge/ {
        root /app/html;
        allow all;
    }

}