-- 아바타 아이템 시드 (SVG 플레이스홀더). price=0은 기본 무료(누구나 장착 가능).
-- asset = 'svg:<key>' — 클라이언트 SVG 렌더러가 key로 그린다. 추후 스프라이트로 교체.
INSERT INTO item (code, name, slot, asset, price, rarity) VALUES
  ('body_basic',   '기본 몸',     'body', 'svg:body_basic',   0,   'common'),
  ('face_smile',   '웃는 얼굴',   'face', 'svg:face_smile',   0,   'common'),
  ('face_cool',    '시크한 얼굴', 'face', 'svg:face_cool',    100, 'common'),
  ('hair_short',   '단발',        'hair', 'svg:hair_short',   0,   'common'),
  ('hair_spiky',   '스파이크',    'hair', 'svg:hair_spiky',   150, 'common'),
  ('hair_long',    '장발',        'hair', 'svg:hair_long',    150, 'rare'),
  ('top_tee',      '티셔츠',      'top',  'svg:top_tee',      0,   'common'),
  ('top_hoodie',   '후드티',      'top',  'svg:top_hoodie',   200, 'common'),
  ('top_suit',     '정장',        'top',  'svg:top_suit',     500, 'rare'),
  ('acc_glasses',  '안경',        'acc',  'svg:acc_glasses',  120, 'common'),
  ('acc_crown',    '왕관',        'acc',  'svg:acc_crown',    1000,'epic'),
  ('body_tan',     '태닝 피부',   'body', 'svg:body_tan',     0,   'common'),
  ('body_pale',    '밝은 피부',   'body', 'svg:body_pale',    0,   'common'),
  ('body_mint',    '민트 피부',   'body', 'svg:body_mint',    300, 'rare'),
  ('body_robot',   '로봇',        'body', 'svg:body_robot',   800, 'epic'),
  ('face_wink',    '윙크',        'face', 'svg:face_wink',    80,  'common'),
  ('face_surprise','놀란 얼굴',   'face', 'svg:face_surprise',80,  'common'),
  ('face_angry',   '화난 얼굴',   'face', 'svg:face_angry',   120, 'common'),
  ('face_cat',     '고양이상',    'face', 'svg:face_cat',     250, 'rare'),
  ('hair_curly',   '곱슬머리',    'hair', 'svg:hair_curly',   150, 'common'),
  ('hair_pony',    '포니테일',    'hair', 'svg:hair_pony',    150, 'common'),
  ('hair_bald',    '민머리',      'hair', 'svg:hair_bald',    50,  'common'),
  ('top_stripe',   '줄무늬티',    'top',  'svg:top_stripe',   150, 'common'),
  ('top_armor',    '갑옷',        'top',  'svg:top_armor',    600, 'rare'),
  ('acc_cap',      '야구모자',    'acc',  'svg:acc_cap',      150, 'common'),
  ('acc_sunglasses','선글라스',   'acc',  'svg:acc_sunglasses',200,'common'),
  ('acc_ribbon',   '리본',        'acc',  'svg:acc_ribbon',   120, 'common'),
  ('acc_headphone','헤드폰',      'acc',  'svg:acc_headphone',250, 'rare'),
  ('acc_halo',     '천사 링',     'acc',  'svg:acc_halo',     800, 'epic')
ON CONFLICT (code) DO NOTHING;
